# Site settings
title: Elsabe Ros
subtitle: I write things
description: > # this means to ignore newlines until "baseurl:" 
  Software engineer, mainly Android, interested in Computer Security and Artificial Inteligence.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://aessedai101.github.io" # the base hostname & protocol for your site
twitter_username: AesSedai101
github_username:  AesSedai101

# Build settings
markdown: kramdown
highlighter: pygments

