# Site settings
title: AesSedai101
#email: 
sub: "Writing about whatever caught my interest"
description: "Writing about whatever caught my interest"
footer_text: 'Theme by <a href="http://github.com/raichur/material-jekyll">Joshua Raichur</a>. '
baseurl: ""
url: "https://aessedai101.github.io"

# Social usernames
twitter_username: AesSedai101
github_username:  AesSedai101
#dribbble_username: geek
#instagram_username: xpl.ore
#email: 

# Build settings
markdown: kramdown
include: ['_pages', '_assets']
exculde: ['.sass_cache', 'README.md']
sass:
  sass_dir: '_assets/_sass'
permalink: "/:title/"

# Defaults
defaults:
  -
    scope:
      path: "_pages"
    values:
      is_in_nav: true
